spring:
  #静态资源处理
  resources:
    #自动默认静态资源，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源（gzip,brotli)解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # thymeleaf配置
  thymeleaf:
    cache: false   #关闭缓存
  # 数据源配置
  #mysql5.7   mysql8用的是cj.jdbc.Driver
  #mysql8加上  ?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
#    password: root
    password: 1234
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分组）
      idle-timeout: 600000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存货时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 心跳测试，测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redis配置
  redis:
    host: 192.168.88.129
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
  #rabbitmq
  rabbitmq:
    host: 192.168.88.129
    port: 5672
    username: guest
    password: guest
    #虚拟主机
    virtual-host: /
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最小数量
        max-concurrency: 10
        #限制消费者每次消费一条消息，然后再消费下一条消息
        prefetch: 1
        #启动时是否默认容器，默认为true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间
        initial-interval: 1000ms
        #重试最大次数，默认3
        max-attempts: 3
        #重试最大时间间隔，默认10000ms
        max-interval: 10000ms
        #重试间隔乘数，比如2.0，第一次就等10s，第二次就等20s，第三次就40s
        multiplier: 1



# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.turbo.seckill.pojo

# Mybatis SQL 打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.turbo.seckill.mapper: debug